//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoChanges.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoChanges.Resources.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability of transfers.
        /// </summary>
        internal static string Availability_of_transfers {
            get {
                return ResourceManager.GetString("Availability_of_transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big risk.
        /// </summary>
        internal static string Big_risk {
            get {
                return ResourceManager.GetString("Big_risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black list of networks.
        /// </summary>
        internal static string Black_list_of_networks {
            get {
                return ResourceManager.GetString("Black_list_of_networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist of coins.
        /// </summary>
        internal static string Blacklist_of_coins {
            get {
                return ResourceManager.GetString("Blacklist_of_coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin.
        /// </summary>
        internal static string Coin {
            get {
                return ResourceManager.GetString("Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comission network.
        /// </summary>
        internal static string ComissionNetwork {
            get {
                return ResourceManager.GetString("ComissionNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comission Spot.
        /// </summary>
        internal static string ComissionSpot {
            get {
                return ResourceManager.GetString("ComissionSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures.
        /// </summary>
        internal static string Futures {
            get {
                return ResourceManager.GetString("Futures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedging.
        /// </summary>
        internal static string Hedging {
            get {
                return ResourceManager.GetString("Hedging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input, output.
        /// </summary>
        internal static string Input_Output {
            get {
                return ResourceManager.GetString("Input_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum commission $.
        /// </summary>
        internal static string Maximum_commission {
            get {
                return ResourceManager.GetString("Maximum_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum volume $.
        /// </summary>
        internal static string Maximum_volume {
            get {
                return ResourceManager.GetString("Maximum_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount $.
        /// </summary>
        internal static string Minimum_amount {
            get {
                return ResourceManager.GetString("Minimum_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum volume $.
        /// </summary>
        internal static string Minimum_volume {
            get {
                return ResourceManager.GetString("Minimum_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers.
        /// </summary>
        internal static string Only_numbers {
            get {
                return ResourceManager.GetString("Only_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit $.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select exchanges.
        /// </summary>
        internal static string Select_exchanges {
            get {
                return ResourceManager.GetString("Select_exchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select options.
        /// </summary>
        internal static string Select_options {
            get {
                return ResourceManager.GetString("Select_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread %.
        /// </summary>
        internal static string Spread {
            get {
                return ResourceManager.GetString("Spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum $.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of lives.
        /// </summary>
        internal static string Time_of_lives {
            get {
                return ResourceManager.GetString("Time_of_lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interexchange scanner.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update period.
        /// </summary>
        internal static string Update_period {
            get {
                return ResourceManager.GetString("Update_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
